# Generated by Django 2.0.7 on 2018-07-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='tasks',
            new_name='todos',
        ),
    ]
